#!/bin/bash
echo "MariaDB密码重置说明"
echo "==================="
echo ""
echo "要重置MariaDB root密码，请按以下步骤操作："
echo ""
echo "1. 停止MariaDB服务："
echo "   sudo systemctl stop mariadb"
echo ""
echo "2. 以安全模式启动MariaDB（跳过权限表）："
echo "   sudo mysqld_safe --skip-grant-tables --skip-networking &"
echo "   # --skip-networking 选项增加安全性，只允许本地连接"
echo ""
echo "3. 连接到MariaDB："
echo "   mysql -u root"
echo ""
echo "4. 在MySQL命令行中执行以下命令："
echo "   USE mysql;"
echo "   UPDATE user SET authentication_string=PASSWORD('040608') WHERE User='root' AND Host='localhost';"
echo "   FLUSH PRIVILEGES;"
echo "   EXIT;"
echo ""
echo "5. 重新启动MariaDB服务："
echo "   # 首先找到mysqld_safe进程并终止它"
echo "   sudo pkill mysqld"
echo "   sudo systemctl start mariadb"
echo ""
echo "6. 验证新密码："
echo "   mysql -u root -p040608 -e 'SHOW DATABASES;'"
echo ""
echo "注意：如果您使用的是MariaDB 10.4或更高版本，密码字段名称可能为"
echo "authentication_string 而不是 password，命令略有不同。"